# Generated by Django 5.1.5 on 2025-02-20 14:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlazingFrameless',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(default='none.jpg', max_length=100, verbose_name='имя_картинки')),
                ('title', models.CharField(max_length=70, verbose_name='заголовок')),
                ('description', models.CharField(default='', max_length=250, verbose_name='описание')),
                ('text', models.TextField(verbose_name='описание')),
                ('created_timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'безрамное_остекление',
                'verbose_name_plural': 'безрамное_остекление',
                'db_table': 'glazing_frameless',
            },
        ),
        migrations.CreateModel(
            name='GlazingAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='преимущество')),
                ('description', models.CharField(max_length=250, verbose_name='описание')),
                ('created_timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='дата создания')),
                ('glazing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='безрамное_остекление', to='home.glazingframeless')),
            ],
            options={
                'verbose_name': 'Преимущества_безрамного_остекления',
                'verbose_name_plural': 'Преимущества_безрамных_остеклений',
                'db_table': 'glazing_advantage',
            },
        ),
    ]
