# Generated by Django 5.1.5 on 2025-02-21 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glazingadvantage',
            options={'verbose_name': 'Преимущества безрамного остекления', 'verbose_name_plural': 'Преимущества безрамных остеклений'},
        ),
        migrations.AlterModelOptions(
            name='glazingframeless',
            options={'verbose_name': 'безрамное остекление', 'verbose_name_plural': 'безрамное остекление'},
        ),
        migrations.AddField(
            model_name='glazingframeless',
            name='image_additional_1',
            field=models.CharField(default='none.jpg', max_length=100, verbose_name='доп картинка №1'),
        ),
        migrations.AddField(
            model_name='glazingframeless',
            name='image_additional_2',
            field=models.CharField(default='none.jpg', max_length=100, verbose_name='доп картинка №2'),
        ),
        migrations.AddField(
            model_name='glazingframeless',
            name='image_additional_3',
            field=models.CharField(default='none.jpg', max_length=100, verbose_name='доп картинка №3'),
        ),
        migrations.AlterField(
            model_name='glazingadvantage',
            name='glazing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glazing_advantage', to='home.glazingframeless'),
        ),
        migrations.AlterField(
            model_name='glazingframeless',
            name='image_name',
            field=models.CharField(default='none.jpg', max_length=100, verbose_name='основная картинка'),
        ),
    ]
