# Generated by Django 5.1.5 on 2025-02-26 11:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_glazingadvantage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlazingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='заголовок')),
                ('image', models.CharField(default='none.jpg', max_length=100, verbose_name='изображение')),
                ('description', models.TextField(verbose_name='описание')),
                ('video_name', models.CharField(default='none.mp3', max_length=100, verbose_name='видео')),
                ('characteristics', models.JSONField(default=dict)),
                ('created_timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Типы остекления',
                'verbose_name_plural': 'Типы остеклений',
                'db_table': 'glazing_type',
            },
        ),
        migrations.CreateModel(
            name='GlazingTypeMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('image_name', models.CharField(default='none.jpg', max_length=100, verbose_name='изображение')),
                ('created_timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='дата создания')),
                ('glazing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glazing_type_movement', to='home.glazingtype')),
            ],
            options={
                'verbose_name': 'Вариант перемещения панели',
                'verbose_name_plural': 'Варианты перемещения панелей',
                'db_table': 'glazing_type_properties',
            },
        ),
    ]
