# Generated by Django 5.1.5 on 2025-02-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_glazingtype_glazingtypemovement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glazingadvantage',
            options={'verbose_name': 'Безрамное остекление - преимущества', 'verbose_name_plural': 'Безрамные остекления - преимущества'},
        ),
        migrations.AlterModelOptions(
            name='glazingframeless',
            options={'verbose_name': 'Безрамное остекление', 'verbose_name_plural': 'Безрамное остекление'},
        ),
        migrations.AlterModelOptions(
            name='glazingtype',
            options={'verbose_name': 'Тип остекления', 'verbose_name_plural': 'Типы остеклений'},
        ),
        migrations.AlterModelOptions(
            name='glazingtypemovement',
            options={'verbose_name': 'Тип остекления - вариант перемещения панели', 'verbose_name_plural': 'Типы остеклений - варианты перемещения панелей'},
        ),
        migrations.AlterField(
            model_name='glazingtype',
            name='video_name',
            field=models.CharField(default='none.mp4', max_length=100, verbose_name='видео'),
        ),
    ]
