# Generated by Django 5.1.5 on 2025-02-28 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_glazingadvantage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glazingtype',
            old_name='image',
            new_name='image_name',
        ),
    ]
